diff --git Makefile Makefile
index 3d984dcfa..444bb98f2 100644
--- Makefile
+++ Makefile
@@ -55,6 +55,8 @@ CEPH_VERSION ?= $(shell . $(CURDIR)/build.env ; echo $${CEPH_VERSION})
 # TODO: ceph_preview tag required for FSQuiesce API
 GO_TAGS_LIST ?= $(CEPH_VERSION) ceph_preview
 
+GOFLAGS="-trimpath=false"
+
 # go build flags
 LDFLAGS ?=
 LDFLAGS += -X $(GO_PROJECT)/internal/util.GitCommit=$(GIT_COMMIT)
@@ -167,7 +169,7 @@ commitlint:
 .PHONY: cephcsi
 cephcsi: check-env
 	if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
-	GOOS=linux go build $(GO_TAGS) -mod vendor -a -ldflags '$(LDFLAGS)' -o _output/cephcsi ./cmd/
+	GOOS=linux go build $(GOFLAGS) $(GO_TAGS) -mod vendor -a -ldflags '$(LDFLAGS)' -o _output/cephcsi ./cmd/
 
 e2e.test: check-env
 	go test $(GO_TAGS) -mod=vendor -c ./e2e
