diff --git Makefile Makefile
index f7157dc84..b07a414f4 100644
--- Makefile
+++ Makefile
@@ -55,6 +55,8 @@ CEPH_VERSION ?= $(shell . $(CURDIR)/build.env ; echo $${CEPH_VERSION})
 # TODO: ceph_preview tag required for FSQuiesce API
 GO_TAGS_LIST ?= $(CEPH_VERSION) ceph_preview
 
+GOFLAGS="-trimpath=false"
+
 # CephCSI currently has 4 modules in these directories.
 GO_MODULES_LIST = ./ e2e/ api/ actions/retest
 
@@ -171,7 +173,7 @@ commitlint:
 .PHONY: cephcsi
 cephcsi: check-env
 	if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
-	GOOS=linux go build $(GO_TAGS) -mod vendor -a -ldflags '$(LDFLAGS)' -o _output/cephcsi ./cmd/
+	GOOS=linux go build $(GOFLAGS) $(GO_TAGS) -mod vendor -a -ldflags '$(LDFLAGS)' -o _output/cephcsi ./cmd/
 
 e2e.test: check-env
 	cd e2e && go test $(GO_TAGS) -mod=vendor -c -o ../e2e.test ./
